### ISSUE TITLE
Non `light` Default Theme Isn't Served On Page Load

### ISSUE THREAD

**Issue by deg4uss3r** [rust-lang/mdBook#1078]
When using the `default-theme` configuration option on `mdbook v0.3.3` the "default theme" is not the theme rendered when opening `book/index.html` or connecting to `localhost:3000` with `mdbook serve` running, it appears to always render `light`. 

here's my book.toml:
```toml
[book]
authors = ["Ricky"]
multilingual = false
src = "src"
title = "Intro To Rust"

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
```

The page shows I have `Ayu` selected as the default them but renders as `light`, tried clearing all caches and removing `book/` and rebuilding. Happening to me on all the following browsers (Safari `13.0.2 (14608.2.40.1.3)`, Firefox Nightly `72.0a1 (2019-10-28) (64-bit)`, Firefox `70.0 (64-bit)`). Image shows `Ayu (default)` but obviously not `Ayu` theme, if I then select it will then display. 

![](https://i.imgur.com/mVrblz8.png)
