### ISSUE TITLE
Publish the mdBook to gh-pages workflow as a separate action

### ISSUE THREAD

**Issue by Kampfkarren** [rust-lang/mdBook#1090]
I'd like to integrate my book as a GitHub pages. This repository already has an action for this: https://github.com/rust-lang/mdBook/blob/master/.github/workflows/deploy.yml

However, I'm required to copy and paste all of this into my own repository, instead of using something simpler like:

```yml
steps:
    - uses: rust-lang/mdbook-build-action@master
```

**Comment by PsiACE** [comment]
Good idea, but I think these two goals are not consistent.

If you just want to deploy a personal book, consider using some more convenient deployment actions and using a pre-built mdBook.

```yml
name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    release:
        name: GitHub Pages
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v1

            - name: Setup mdBook
              run: |
                  export MDBOOK_VERSION="v0.3.5"
                  export MDBOOK_TARBALL="mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
                  wget -q "https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/${MDBOOK_TARBALL}"
                  tar -zxvf "${MDBOOK_TARBALL}"
                  rm "${MDBOOK_TARBALL}"
                  mkdir ~/bin
                  mv ./mdbook ~/bin/
                  echo "::add-path::~/bin"

            - name: Build Book
              run: |
                  mdbook build
                  cp ./config/CNAME ./book/CNAME

            - name: Deploy Book
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./book
                  SCRIPT_MODE: true
              run: |
                  wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
                  bash ./entrypoint.sh
```

Faster and more suitable.

**Comment by Kampfkarren** [comment]
I figured that out when I tried to integrate it, sadly. Any chance you could upload that somewhere though so using it is as easy as the snippet in the OP? 😀

**Comment by PsiACE** [comment]
Oversimplification may mean higher coupling.

**Comment by peaceiris** [comment]
I published the GitHub Actions for mdBook.

[peaceiris/actions-mdbook: GitHub Actions for mdBook (rust-lang/mdBook)](https://github.com/peaceiris/actions-mdbook)

We can run **mdBook** on a virtual machine of **GitHub Actions** by this action. Linux, macOS, and Windows are supported.

Here is an example workflow to deploy to GitHub Pages.

```yaml
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'

    - run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./book
```

Fetch the latest version of mdBook.

```yaml
- name: Setup mdBook
  uses: peaceiris/actions-mdbook@v1
  with:
    mdbook-version: 'latest'
```

- [peaceiris/actions-gh-pages: GitHub Actions for GitHub Pages](https://github.com/peaceiris/actions-gh-pages)
