### ISSUE TITLE
Deploy mdbook help

### ISSUE THREAD

**Issue by emilianonatella** [rust-lang/mdBook#1165]
Hi everyone, I have problems with the Deploying of my book on GitHub Pages.
Could any of you explain to me step by step how to deploy in the simplest possible hands?

**First try**
*Deploying Book to GitHub Pages with travis.yml*.
I have tried with tokens and travis.yml but something is not working.

 1. Go to Travis-ci.com and Sign up with GitHub.
 2. Accept the Authorization of Travis CI. You’ll be redirected to GitHub.
 3. Click on your profile picture in the top right of your Travis Dashboard, click the green Activate button, and select the
    repositories you want to use with Travis CI.
 4. Generate new token  
 5. > Go to your repository's Travis CI settings page and add an environment variable named GITHUB_TOKEN that is marked secure and not shown in the logs. How?

 5. Create file travis.yml on my local folder or in remote GitHub repo folder? 
 6. After what i have to do?

The code that I put into travis.yml
```
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: path / to / mybook / book
  keep-history: false
  on:
    branch: master
```
It's my first time on GitHub and i don't know any commands, I'm learning now.

**Second try**
*Deploying to GitHub Pages manually.*
The first time it worked.
But creating a new repository gives me an error regarding the temporary folder (number 7).
What is the correct procedure? 
I list all the steps I took to generate the book

 1. cloned the repo locally `$ git clone ... repo.git`
 2. `$ mdbook init --theme`
 3. I added all the * .md files in the src / folder
 4. I modify the SUMMARY.md
 5. ```$ git status
     $ git add -A
     $ git push```
 6. I create the gh-pages branch `git branch gh-pages`
 7. `$ git worktree add / tmp / book gh-pages`
         `fatal: '/ tmp / book' already exists`
    If I use another directory, for example, `tmp / book2`, it goes on correctly for a few steps
 8. `$ mdbook build`
 9. `$ rm -rf / tmp / book2 / *`
 10. `$ cp -rp book2 / * / tmp / book2 /` Another error here!
         `cp: book2/*: No such file or directory`. What am I doing wrong in the linux command?
 11. `$ cd / tmp / book2`
 12. `$ git add -A`
 13. `$ git commit 'new book message'`
 14. `$ git push origin gh-pages`
 15. `$ cd -`

**Comment by ehuss** [comment]
It looks like maybe you got stuck around step 5?  Travis has step-by-step instructions on adding an environment variable here: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings.  It's probably easiest to use the Travis UI (the "Settings" page).  You should be able to enter the environment variable `GITHUB_TOKEN` with the token you copied from GitHub.

The `.travis.yml` file should go in the root of your git repository.  You should add it with git to the master branch, commit it, and push that to your github repository.

**Comment by emilianonatella** [comment]
Thank you for your answer, I managed to create the environment variable with the name **"$GITHUB_TOKEN"** or I didn't have to enter the character **"$"** because does it add it automatically?

> The .travis.yml file should go in the root of your git repository. You should add it with git to the master branch, commit it, and push that to your github repository.

I think I did it correctly, created on my computer and put commands:
```
git add -A
git commit -m
git push
```

I don't understand the next steps well.
Create the book?
`$ mdbook build`
And then? add, commit and push to the master branch the new file?

Also what do I need the token for? When is it used?

**Comment by ehuss** [comment]
Yea, you don't need the `$`.  That is just a convention for representing an environment variable. In various environments (particularly shells like bourne shell or bash), the `$` indicates variable substitution ("place the contents of the variable here").

When you create a book (such as with `mdbook init`), it creates a file named `book.toml` which contains information about your book (the name, etc.), and a `src` directory with the source of the book.  You'll need to add those to the git repo and commit them.

Your `.travis.yml` file will need to have a step that builds the book (convert it to HTML) with `mdbook build`.  The HTML files are stored in a directory named `book`.  The `deploy` step on Travis will then take the contents of that `book` directory and automatically push them to the gh-pages branch on GitHub.

You need the token so that Travis has the permission to modify your repository on GitHub. GitHub only allows modifications from authorized users.

**Comment by XAMPPRocky** [comment]
@emilianonatella This is doesn't solve the issue around the documentation, but you might be interested in the GitHub Action I wrote to build and deploy mdbook projects using GitHub Actions, which requires zero configuration, just create a `workflows/deploy_mdbook.yml` with the following. https://github.com/XAMPPRocky/deploy-mdbook

```yaml
name: Deploy mdBook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/deploy-mdbook@v1.1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by avisionh** [comment]
I recently came had the same issue and resolved it for my [repo](https://github.com/avisionh/training-git/tree/master) by writing the following in my `.travis.yml` file (as well as deploying to GitHub Pages via the `gh-pages` branch). I've set-up a PR to describe what I did, #1373. Hope this helps. :) 

```yml
language: rust
os: linux
dist: xenial

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

# ensure book builds and tests pass
script:
  - mdbook build && mdbook test

# publish to GitHub Pages after successful run
deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: book
  keep_history: false
  on:
    branch: master
  target_branch: gh-pages
```
