### ISSUE TITLE
Ability for run Rust code block outside sanbox environment

### ISSUE THREAD

**Issue by TuyenTk** [rust-lang/mdBook#1365]
Sometime I want to run Rust code on my local machine, directly from mdBook, so that I don't need to copy the code to IDE. I'm imagine it would be great if mdBook has that feature, with some config like this:

```toml
[output.html.playground]
whitelist-hosts = ["localhost", "mybook.local"]
```

or like this:

```toml
[output.html.playground]
run-on-local = true
```

Of course this will invole the task how we can determine if a running request is came from local or not. I'll don't know if it is possible. Hope that I'm not alone want this feature.
