### ISSUE TITLE
Edit link to gitlab ide

### ISSUE THREAD

**Issue by chriswalg** [rust-lang/mdBook#1370]
It would be great to have a edit link to gitlab ide

example link:
https://gitlab.com/-/ide/project/$projectName/$repoName/edit/master/-/docs/$fileName

**Comment by ehuss** [comment]
Closing, as I believe this is now implemented via #1506.  The template would look something like:

```toml
# book.toml
[output.html]
edit-url-template = "https://gitlab.com/-/ide/project/username/project-name/edit/master/-/{path}"
```
