### ISSUE TITLE
Provide a default include path, so that it doesn't need to be relative to the current file

### ISSUE THREAD

**Issue by brizental** [rust-lang/mdBook#1512]
This is a minor feature request.

I'd like to be able to define a path where mdbook will look for includes, this way, if I change the folder structure the include paths don't break necessarily.

I would be happy to work on this feature, in case it is decided that it is ok to implement it :)

**Comment by daprilik** [comment]
At minimum, it would be great if `{{ #include /book/root/relative/path }}` worked correctly (much like book-root relative markdown links work).

I've worked around this using a custom pre-processor which does this translation manually, but this really seems like something that `mdbook` should support out-of-the-box.

**Comment by alonbl** [comment]
Hi,
I also bump into this issue, not sure if it is the same, during build I generate files into builddir, I would like to include these from a file that is in srcdir, currently it is not possible as search is always relative to the file.
Can we have something like in C? have `include ""` which is relative and `include <>` which searches include directories?
Or... having attributes available for the include? currently the variables are resolved after the links...
Thanks!

**Comment by alonbl** [comment]
Hello,

I resolved this by running the variables preprocessor twice — once before the links preprocessor and once after it.

While doing this, I noticed an issue with the plugin interface: the plugin does not receive its own name (i.e., argv[0]). As a result, even if I assign it a different section name, it still reads from `preprocessor.variables.variables`.

It would be better if the plugin used its own name and referenced something like `preprocessor.variables-pre.variables` instead.

```toml
[preprocessor.variables-pre]
command = "@MDBOOK_VARIABLES_EXECUTABLE@"
before = [
    "links",
]

[preprocessor.variables]
command = "@MDBOOK_VARIABLES_EXECUTABLE@"
after = [
    "links",
]

[preprocessor.variables.variables]
BUILD_DIR = "@CMAKE_BINARY_DIR@"
```

```markdown
{{#include {{ BUILD_DIR }}/generated/data.md}}
```
