### ISSUE TITLE
Multi language book option

### ISSUE THREAD

**Issue by Azgrom** [rust-lang/mdBook#1521]
Accordingly to the mdBook guide:

> - language: The main language of the book, which is used as a language attribute <html lang="en"> for example.

And it is defined at `book.toml`:
```toml
[book]
language = "en"
```

So, I wonder if there is plans to make possible something like:
```toml
[book]
language = ["en", "pt-br"]
```
Such that one could press a button and the book would show its content in the different language/idiom.
Is there any alternative backend that do it? If not, what do you think of this idea?
