### ISSUE TITLE
Misleading book.toml related error message

### ISSUE THREAD

**Issue by Azgrom** [rust-lang/mdBook#1522]
Just on the subject of #1521, if I wrongly define the `book` section such as below, mdBook returns an inaccurate error message:
```toml
[book]
authors = ["Rafael Lúcio"]
src = "docs/src"
language = ["en", "pt-br"]
multilingual = true
title = "CET961 - Engenharia Assistida por Computador"
```
```bash
$ mdbook build
2021-05-05 10:41:52 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/rafael/Documents/Repos/CAE/src" directory
2021-05-05 10:41:52 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```
It cannot open `SUMMARY.md` at `src` because it is defined to be at `docs/src`.

If I set the language correctly it runs perfectly. For some reason a syntax error at the `language` field makes mdbook not read correctly the `src` field.

`mdbook build` here is just and example. This same message error does appear if the `clean`, `watch` or `serve` subcommands are executed.
