### ISSUE TITLE
Add option to link to source in file snippets

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [rust-lang/mdBook#1602]
I am using mdBook to write documentation about a code framework and include code snippets from an example project. It would be nice if those code snippets have a button that links to the line start in the GitHub repository, so the user can easily view the context of the included code snippet and knows what file it is in.

I suggest adding an option to the preprocessor config to enable this, and when enabled it would add an extra button next to the "copy to clipboard" button with a link that's defined in book.toml. That link would optionally point to an exact line if the snippet is a portion of a file and an appropriate url is configured.

Configuration example:
```toml
[preprocessor.links]
source-code-url = "https://github.com/USER/REPO/blob/BRANCH/{path}"
source-code-url-with-line = "https://github.com/USER/REPO/blob/BRANCH/{path}#L{line_no}"
```
