### ISSUE TITLE
Open link in a new tab

### ISSUE THREAD

**Issue by aiden-leong** [rust-lang/mdBook#1665]
```toml
[output.html]
open-internal-url-in-new-tab = false
open-external-url-in-new-tab = true
```
```markdown
[Link](./another-page.html) -> Jump in current tab
[Link](https://www.example.com/) -> Open a new tab
```
