### ISSUE TITLE
book.toml Configuration file failure

### ISSUE THREAD

**Issue by ljrxzr** [rust-lang/mdBook#1774]
Does v0.4.16 still read information from book.toml? When I switch from 0.4.15 to 0.4.16, the previous changes are scrapped

**Comment by ehuss** [comment]
Hm, that's a little worrisome.  I can't reproduce the issue, though.  I tried with a book.toml of:

```toml
[book]
title = "foo"

[output.html]
no-section-label = true
```

And the book rendered without the section labels.
Can you provide a more complete reproduction?  Can you say more about exactly what you did?

**Comment by ljrxzr** [comment]
> Hm, that's a little worrisome. I can't reproduce the issue, though. I tried with a book.toml of:
> 
> ```toml
> [book]
> title = "foo"
> 
> [output.html]
> no-section-label = true
> ```
> 
> And the book rendered without the section labels. Can you provide a more complete reproduction? Can you say more about exactly what you did?

This is my profile

```toml
[book]
authors = []
language = "zh"
multilingual = false
src = "src"

[output.html]
no-section-label = true

[output.html.print]
enable = false
```

After my attempts, here is the problem

```toml
[output.html.print]
enable = false
```

This is the configuration I had in the previous version.

`enable = false` generated an error，disables most configurations, including `no-section-label = true`
