### ISSUE TITLE
feature request: Generate PDF with outlines intact

### ISSUE THREAD

**Issue by schwrzstrbn** [rust-lang/mdBook#1817]
I think it would be awesome if we can generate PDF with outlines intact. Also a command to generate pdf with outlines intact. I hope this idea aligns with the mdbook team.

**Comment by ISSOtm** [comment]
I'm not sure what you mean by "outlines"?

**Comment by schwrzstrbn** [comment]
![Screenshot_2022-06-23-09-19-55-31_c0fc23361849dfc0a4b4c6dd2adcac79.png](https://user-images.githubusercontent.com/45195351/175187157-46cda3a8-dde0-4a60-8de0-fed0fd6614c0.png)

This is a screenshot I took from my pdf/ebook reader on my phone. What I meant by `Outlines` is exactly this. Page links with title for faster and efficient navigations within pdf/ebook files.

**Comment by schwrzstrbn** [comment]
> I'm not sure what you mean by "outlines"?

Maybe adding a new keyword in `output.html.print`, like `outline = true/false`

```toml
[output.html.print]
enable = true
page-break = true
outline = true # new keyword to include the 'ToC' in pdf print.
```
