### ISSUE TITLE
Incorrect color for print page inline code blocks in headers

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#1933]
Inline code blocks in headers are rendered with a black background on Safari and Chrome. This does not seem to affect Firefox.

Chrome:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/43198/203125577-17847c3a-04d9-4efa-9fb6-e174646258c6.png">

Safari:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/43198/203125700-b418fde8-bd27-4c17-8533-44c595a10ba8.png">

Firefox:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/43198/203125786-bad89449-00f4-4d28-b46c-393fc16685b2.png">

**Comment by quackenbush** [comment]
I suspect the problem stems from src/theme/css/print.css

You might have accidentally turned on 'print' preview layout in your CSS inspector in those browsers.

Can the background-color be removed, or was there a reasoning for this during print?

```css
code {
    background-color: #666666;
    border-radius: 5px;

    /* Force background to be printed in Chrome */
    -webkit-print-color-adjust: exact;
}
```
