### ISSUE TITLE
Providing your own command for a preprocessor doesn't evaluate $ENV_VARS

### ISSUE THREAD

**Issue by slmgc** [rust-lang/mdBook#2040]
### Problem

Currently, there is no way to define a custom preprocessor in case the command-line arguments contain an environment variable which needs to be evaluated as a part of the script's path.

### Steps

Adding a preprocessor to a `book.toml`:

```toml
[preprocessor. example]
command = "python $HOME/example.py" # that doesn't work
```

mdbook build fails with an error:

```sh
Python: can't open file '$HOME/example.py' # please note that $HOME env var was not evaluated
```
Using a relative path or an absolute path works fine:

```toml
command = "python example.py" # that works
command = "python /absolute/path/example.py" # that works fine
command = "python ../../relative/path/example.py" # that works as well
```

### Version

```text
mdbook v0.4.27
```
