### ISSUE TITLE
How to change max content width of single page?

### ISSUE THREAD

**Issue by armoha** [rust-lang/mdBook#2098]
### Question

I want wide width for overview table page, but don't need to change width of other pages.

Example: https://armoha.github.io/eud_book_en/

```css
/* theme/css/variables.css */
:root {
    /* this applies to every pages */
    --content-max-width: 1350px;
}
```

### Version

```text
mdbook v0.4.30
```
