### ISSUE TITLE
Menu bar shakes when swiping pages in Safari

### ISSUE THREAD

**Issue by evibhm** [rust-lang/mdBook#2119]
### Problem

Menu bar shakes when swiping pages in Safari

gif:
![mdbook-swip-bug](https://github.com/rust-lang/mdBook/assets/60606009/6d7da67d-5efc-4a4b-9419-4d1defe6e036)

### Steps

1. Find a relatively long page in the pages generated by mdbook and slide it.

### Possible Solution(s)

The style

```css
#menu-bar.sticky,
.js #menu-bar-hover-placeholder:hover + #menu-bar,
.js #menu-bar:hover,
.js.sidebar-visible #menu-bar {
    position: -webkit-sticky;
    position: sticky;
    top: 0 !important;
}
```

conflict with
```css
#body-container {
    overflow-x: clip;
}
```

### Notes

macOS Ventura 13.1
Safari Version 16.2

### Version

```text
mdbook v0.4.30
```
