### ISSUE TITLE
Enhancing dark-mode themes with `color-scheme` implementation in CSS

### ISSUE THREAD

**Issue by GiorgioReale** [rust-lang/mdBook#2132]
### Problem

When mdBook is displayed with a dark theme, some elements of the browser remain rendered in a light theme, which is unfortunate since most browsers support the implementation of `color-scheme: light | dark;` in CSS.

Example:
Currently, in the dark theme, the scrollbars are displayed in a light color.
![](https://github.com/rust-lang/mdBook/assets/77497498/2c4f12b0-58fc-49ec-bb0e-5d04c0b67d1d)

However, it would be sufficient to implement `color-scheme: dark;` on the `html` tag to make them dark for browsers that support it (e.g., Chrome or Edge - not Firefox).
![](https://github.com/rust-lang/mdBook/assets/77497498/7ea36a8b-1631-403e-b21c-926bc9ff3142)

### Proposed Solution

To resolve these issues, the following two steps can be taken:

1. Add the following CSS rules for each theme class in the `src/theme/css/variables.css` file:
```css
.coal {
  --color-scheme: dark;
}

.navy {
  --color-scheme: dark;
}

.ayu {
  --color-scheme: dark;
}

/* For completeness, declare the rule also for light themes. */
.light {
  --color-scheme: light;
}

.rust {
  --color-scheme: light;
}
```

2. Add the following CSS rule for `:root` in the `src/theme/css/general.css` file:
```css
:root {
  color-scheme: var(--color-scheme);
}
```
