### ISSUE TITLE
Is it possible to perform tilde expansion inside `command` field inside `book.toml`?

### ISSUE THREAD

**Issue by your-diary** [rust-lang/mdBook#2138]
### Question

According to [*Provide Your Own Command*](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html?highlight=command#provide-your-own-command), the command for a preprocessor can be specified as in
```toml
[preprocessor.random]
command = "python random.py"
```

Is it possible to perform tilde expansion in this context? I'd like to write like
```toml
[preprocessor.random]
command = "~/programs/a.out"
```

without wrapping it within a shell (e.g. `command = "bash -c '~/programs/a.out'"`).
