### ISSUE TITLE
Add `expand` option to `output.html.fold` feature

### ISSUE THREAD

**Issue by julio4** [rust-lang/mdBook#2219]
### Problem

```toml
[output.html.fold]
enable = true
```
This enable foldable sections in the sidebar, however they are all unfolded by default.

### Proposed Solution

```toml
[output.html.fold]
enable = true
expand = true
```

A new option `output.html.fold.expand` (default to `false`) that expand all foldable sections by default would be nice.

### Notes

Could be slightly related to #2177
