### ISSUE TITLE
Configuration values must be lowercase when set with environment variables

### ISSUE THREAD

**Issue by mgeisler** [rust-lang/mdBook#2281]
### Problem

As far as I can tell from [5.2.4. Environment Variables](https://rust-lang.github.io/mdBook/format/configuration/environment-variables.html), it it not possible to override a key like

```toml
[output.pandoc.profile.pdf.variables]
CJKmainfont = "Noto Serif CJK SC"
CJKsansfont = "Noto Sans CJK SC"
CJKmonofont = "Noto Sans Mono CJK SC"
```

via the environment variables?

That is, the environment variables only allow for setting all-lowercase configuration values.

### Possible Solution(s)

An alternative would be to specify the whole of `output.pandoc.profile.pdf.variables` with the JSON syntax. A slight downside of this is that the user will have to repeat the values that are unchanged.

### Notes

I ran into this in https://github.com/google/comprehensive-rust/pull/1572 where we're experimenting with rendering a PDF using [mdbook-pandoc](https://github.com/max-heller/mdbook-pandoc).
