### ISSUE TITLE
No RTL Support & Search not working for languages like arabic or persian!

### ISSUE THREAD

**Issue by nimafanniasl** [rust-lang/mdBook#2316]
### Problem

Hey! I'm working on a website with mdBook that is written in Persian and I stumbled upon these issues:

First: There is no RTL support. I fixed the problem at least for the content itself in the book with this CSS:

```css
#content > main:nth-child(1) > * {
    text-align: start;
    unicode-bidi: plaintext;
}
```

I think it's a simple fix, but it's really needed!

Second problem:
Search doesn't work for Arabic/Persian text but works perfectly for English!

![Screenshot from 2024-02-13 22-36-07](https://github.com/rust-lang/mdBook/assets/76901932/f8167953-d6f4-470d-b034-e676c9ff4cac)

### Steps

1. Make a new project
2. Write some Persian/Arabic Text in it
3. Search for the Persian/Arabic Text

### Version

```text
mdbook v0.4.37
```
