### ISSUE TITLE
Cannot load custom font files with 'mdbook serve' on macOS

### ISSUE THREAD

**Issue by b1nhack** [rust-lang/mdBook#2405]
### Problem

On macOS, custom font files fail to load when previewing the page, while testing the same source files on Windows shows the fonts loading correctly.

### Steps

1. Place the font files into `theme/fonts/`
2. Create a `theme/fonts/fonts.css` file and paste the following content:
```css
/* JetBrains Mono is licensed under the SIL Open Font License 1.1 */

@font-face {
	font-family: "JetBrains Mono";
	font-style: normal;
	font-weight: normal;
	font-display: swap;
	src: url("JetBrainsMono-Regular.woff2") format("woff2");
}

@font-face {
	font-family: "JetBrains Mono";
	font-style: italic;
	font-weight: normal;
	font-display: swap;
	src: url("JetBrainsMono-Italic.woff2") format("woff2");
}

body {
    font-family: "JetBrains Mono", monospace;
    font-size: 2.5em;
    line-height: 1.2;
}
```
3. mdbook serve --open

### Version

```text
mdbook v0.4.40
```
