### ISSUE TITLE
Numbered sections?

### ISSUE THREAD

**Issue by StefanSalewski** [rust-lang/mdBook#2499]
### Question

While most mdbooks are using section titles without numbers, I really prefer numbers. Of course they consume some horizontal space, but they make it more clear what we are actually currently reading. Without numbers, I often have the problem that for sub-sub-sub-sections the font becomes small, and a title looks like just ordinary text. For me the numbers make the structure of the document more obvious, the various font sizes feel not sufficient for me. Well, and I think that LaTeX documents and most ordinary books use numbered sections as well. So I start writing my book with manually inserted numbers, see https://rust-for-c-programmers.salewskis.de/

The problem now is, that I would like to reorder chapters :-(

With Asciidoctor this was very easy due to autonumbering. What is your recommendation? Might it be possible in future that mdbook will support autonumbering? If not, is there already a tool available? 

### Version

```text

```

**Comment by AdrienDerobert** [comment]
See this issue for a simple fix with css: #723

**Comment by AdrienDerobert** [comment]
This css snipet does work i tested it adds numbers to headings like this:
```md
# A Title
## A Subtitle
## Another subtitle
# Another Title
```

```
1: A Title.
1.1: A Subtitile.
1.2: Another Subtitle.
2: Another Title.
```

Although in its current state it only goes two level deep you would need to add futher css in the same vein for it to work...

**Comment by AdrienDerobert** [comment]
Example for 3 level deep:
```css
body {
    counter-reset: section -1;
}
h1 {
    counter-reset: subsection 0;
    counter-reset: subsubsection 0;
}
h2 {
    counter-reset: subsubsection 0;
}
h1::before {
    counter-increment: section;
    content: counter(section) ": ";
}
h2::before {
    counter-increment: subsection;
    content: counter(section) "." counter(subsection) ": ";
}
h3::before {
    counter-increment: subsubsection;
    content: counter(section) "." counter(subsection) "." counter(subsubsection) ": ";
}
```
