### ISSUE TITLE
Add user-extensible buttons

### ISSUE THREAD

**Issue by mattico** [rust-lang/mdBook#694]
I noticed that rust-by-example is overriding index.hbs just to add a github button back to its repo: https://github.com/rust-lang/rust-by-example/commit/abbaef0a668bc8293420536fd81be59486429e2a

It would be nice to add an extension point to the theme so user's can do this more easily without needing to copy the template.

First draft solution:

```hbs
<div class="right-buttons">
    {{#each right_buttons}}
    <a href="{{href}}" title="{{title}}" aria-label="{{title}}">
        {{#if fa}}
        <i class="fa fa-{{fa}}"></i>
        {{#else}}
        <img class="icon-img" src="{{icon}}"/>
        {{/if}}
    </a>
    {{/each}}
    {{! Special case this for the padding style, or allow user-configurable id or class? }}
    <a href="print.html" title="Print this book" aria-label="Print this book">
        <i id="print-button" class="fa fa-print"></i>
    </a>
</div>
```

```toml
[[output.html.header.icons.left]]
href = "https://github.com/my-project/my-repo"
title = "Contribute to this project"
fa = "github" # use a FontAwesome icon
# icon = "https://my-url.com/icon.png # or an image url?
```
