### ISSUE TITLE
GitLab guide for continuous integration

### ISSUE THREAD

**Issue by kravemir** [rust-lang/mdBook#813]
I'm considering to use mdBook for documentation of my project hosted on Gitlab, in combination with Gitlab Runner and Gitlab Pages.

In [continuous-integration.md](https://github.com/rust-lang-nursery/mdBook/blob/877bf37d18fb4ab533927b7980ef3794cfc9313b/book-example/src/continuous-integration.md) there's example only for Travis CI and GitHub Pages.

It would be nice to have also guide showing how to setup CI with Gitlab (Runner, Pages).

**Comment by Michael-F-Bryan** [comment]
Translating the Travis example to `gitlab-ci.yml` should be pretty straightforward. We actually use it at work for some internal documentation and the only pain point I had was getting caching right. 

I'll see if I can find my `gitlab-ci.yml` and add a simple GitLab CI example to the user guide.

**Comment by kravemir** [comment]
So far, I had used following setting, which I had found somewhere else:

```
pages:
  # https://hub.docker.com/_/rust/
  image: "rust:1.30.1-stretch"
  stage: pages
  script:
    - mkdir public-tmp
    - cargo install mdbook --no-default-features
    - ./bin/copyJavadocToBook.sh
    - mdbook build docs
    - cp -r docs/book/* public-tmp
    - mv public-tmp public
    - find $PWD/public
  artifacts:
    paths:
      - public
```

I'll merge current with your example to get best results.
